app.config(["$routeProvider",function($routeProvider){
	$routeProvider
	.when("/home",{
		templateUrl:"html/home.html",
		controller:"homeController"
	})
	.when("/jiaose",{
		templateUrl:"html/jiaose.html",
		controller:"jiaoseController"
	})
	.when("/guanliyuan",{
		templateUrl:"html/guanliyuan.html",
		controller:"guanliyuanController"
	})
	.when("/zifeiguanli",{
		templateUrl:"html/zifeiguanli.html",
		controller:"zifeiguanliController"
	})
	.when("/zhangwu",{
		templateUrl:"html/zhangwu.html",
		controller:"zhangwuController"
	})
	.when("/yewu",{
		templateUrl:"html/yewu.html",
		controller:"yewuController"
	})
	.when("/zhangdan",{
		templateUrl:"html/zhangdan.html",
		controller:"zhangdanController"
	})
	.when("/baobiao",{
		templateUrl:"html/baobiao.html",
		controller:"baobiaoController"
	})
	.when("/geren",{
		templateUrl:"html/geren.html",
		controller:"gerenController"
	})
	.when("/xiugai",{
		templateUrl:"html/xiugai.html",
		controller:"xiugaiController"
	})
	.when("/role_modi",{
		templateUrl:"html/role_modi.html",
		controller:"role_modiController"
	})
	.when("/role_add",{
		templateUrl:"html/role_add.html",
		controller:"role_addController"
	})
	.when("/admin_add",{
		templateUrl:"html/admin_add.html",
		controller:"admin_addController"
	})
	.when("/admin_modi",{
		templateUrl:"html/admin_modi.html",
		controller:"admin_modiController"
	})
	.when("/fee_add",{
		templateUrl:"html/fee_add.html",
		controller:"fee_addController"
	})
	.when("/fee_modi",{
		templateUrl:"../html/fee_modi.html",
		controller:"fee_modiController"
	})
	.when("/account_add",{
		templateUrl:"html/account_add.html",
		controller:"account_addController"
	})
	.when("/account_modi",{
		templateUrl:"html/account_modi.html",
		controller:"account_modiController"
	})
	.otherwise({
		redirectTo:'/home'
	});
	
}])
